"""metric deployment link

Revision ID: 24861727ed25
Revises: 9407ef90f9f5
Create Date: 2026-09-02 16:20:41.384224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24861727ed25'
down_revision: Union[str, Sequence[str], None] = '9407ef90f9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('deployment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'metrics', 'deployments', ['deployment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_column('metrics', 'deployment_id')
    # ### end Alembic commands ###
