"""metrics table

Revision ID: 9407ef90f9f5
Revises: 76a83c527317
Create Date: 2026-09-02 15:55:02.497874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9407ef90f9f5'
down_revision: Union[str, Sequence[str], None] = '76a83c527317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.Enum('DEVELOPMENT', 'STAGING', 'PRODUCTION', name='environment', native_enum=False, length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('throughput_rpm', sa.Float(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_model_time', 'metrics', ['model_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_model_time', table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
